<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>EndcordInstaller</RootNamespace>
    <AssemblyName>EndcordInstaller</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="InstallerGUI.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="dist\version.json" />
    <EmbeddedResource Include="dist\patcher.js" />
    <EmbeddedResource Include="dist\patcher.js.map" />
    <EmbeddedResource Include="dist\preload.js" />
    <EmbeddedResource Include="dist\preload.js.map" />
    <EmbeddedResource Include="dist\renderer.js" />
    <EmbeddedResource Include="dist\renderer.js.map" />
    <EmbeddedResource Include="dist\renderer.css" />
    <EmbeddedResource Include="dist\renderer.css.map" />
  </ItemGroup>
</Project>
